title: Science Portal
url: "https://physymmetry.org"
baseurl: ""  # Buranı tamamilə boş saxla (dırnaqların içi boş olsun)
logo: "/assets/images/logo.png"
title: "The Symmetry of Physics"

# Məqalələri tapması üçün bu sətirləri mütləq əlavə et:
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

future: true


