title: Science Portal
baseurl: "/science" # Repozitoriyanın adı 'science' olduğu üçün bu vacibdir
url: "https://azerinyuton.github.io"

# Məqalələri tapması üçün bu sətirləri mütləq əlavə et:
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

future: true
